# Generated by Django 4.2.2 on 2023-08-03 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default='articulo/imagen.jpg', null=True, upload_to='articulo')),
                ('estado', models.BooleanField(default=True)),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('categoria', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulo.categoria')),
            ],
            options={
                'ordering': ('-publicado',),
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('articulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='articulo.articulo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('articulo', 'usuario')},
            },
        ),
    ]
