# Generated by Django 4.2.2 on 2023-07-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_calificacion_delete_noticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='valor',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
