# Generated by Django 4.2.2 on 2023-07-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_alter_calificacion_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='articulo.articulo'),
        ),
    ]
